Instll issues

diff --git a/.github/workflows/pylint_check.yaml b/.github/workflows/pylint_check.yaml
--- a/.github/workflows/pylint_check.yaml
+++ b/.github/workflows/pylint_check.yaml
@@ -64,13 +64,13 @@ jobs:
         run: 'python3 -m pip install --no-cache-dir pygdal==2.2.3.5'
       - name: Install system requirements from source
         shell: bash
-        run: '[ -s "packages.txt" ] && (sudo cat packages.txt | xargs apt-get install -y --no-install-recommends) || (echo "Failed to install additional packages")'
+        run: '[ -s "packages.txt" ] && (cat packages.txt | sudo xargs apt-get install -y --no-install-recommends) || (echo "Failed to install additional packages" && exit 1)'
       - name: Install Python requirements from source
         shell: bash
-        run: '[ -s "requirements.txt" ] && (python3 -m pip install --no-cache-dir -r requirements.txt) || (echo "Failed to install Python requirements")'
+        run: '[ -s "requirements.txt" ] && (python3 -m pip install --no-cache-dir -r requirements.txt) || (echo "Failed to install Python requirements" && exit 1)'
       - name: Run action pylint script
         shell: bash
-        run: '[ -s ".github/workflows/action_pylint.sh" ] && (chmod +x ".github/workflows/action_pylint.sh" && ./.github/workflows/action_pylint.sh) || (echo "Error running shell script")'
+        run: '[ -s ".github/workflows/action_pylint.sh" ] && (chmod +x ".github/workflows/action_pylint.sh" && ./.github/workflows/action_pylint.sh) || (echo "Error running shell script" && exit 1)'
       - name: Fetching pylint.rc file
         run: wget https://raw.githubusercontent.com/AgPipeline/Organization-info/master/pylint.rc
         if: ${{ matrix.name }} == "pylint"
